friends = ["Kevin", "Karen", "Jim", "Oscar", "Toby"]
print(friends)
print(friends[0])
print(friends[1])       
print(friends[2])
print(friends[3])       
print(friends[4])
print(friends[-1])
print(friends[-2])
print(friends[-3])  
print(friends[-4])
print(friends[-5])
print(friends[1:4]) 
print(friends[1:])
print(friends[:4])  
print(friends[:])
friends[1] = "Mike"
print(friends)
lucky_numbers = [4, 8, 15, 16, 23, 42]
friends.extend(lucky_numbers)   
print(friends)
friends.append("Creed")     
print(friends)
friends.insert(1, "Kelly")  
print(friends)
friends.remove("Jim")
print(friends)
friends.pop()
print(friends)
print(friends.index("Oscar"))
print(friends.count("Kevin"))

friends = ["Kevin", "Karen", "Jim", "Oscar", "Toby"]
friends.sort()
print(friends)      
lucky_numbers = [4, 8, 15, 16, 23, 42]
lucky_numbers.sort()
print(lucky_numbers)    
lucky_numbers.reverse()
print(lucky_numbers)
friends.reverse()
print(friends)  
friends2 = friends.copy()
print(friends2)
